repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.5.0
    hooks:
      - id: reorder-python-imports
        args: ["--application-directories", "src"]
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
        additional_dependencies: [flake8-bugbear]
        language_version: python3
